require 'pry'
require 'nokogiri'
require 'open-uri'
require 'json'
require 'net/http'

require_relative '../lib/cli'
require_relative '../lib/park'
require_relative '../lib/scraper'
require_relative '../lib/version'
